name: Build Test on PR

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - "1.13"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.elixir }}
          push: false
          tags: articulate/articulate-elixir:${{ matrix.elixir }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=registry,ref=articulate/articulate-elixir:${{ matrix.elixir }}
          cache-to: type=inline
