name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "1.9"
          - "1.10"
          - "1.11"
          - "1.12"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
